### PR TITLE
Split up release process into PR + release

### PR DESCRIPTION
**Pull request by rkalis**
Notes:

- This will publish on "push" to `main`, and since `main` is protected, this means a PR has been merged (see https://github.com/orgs/community/discussions/26724).
- In order for GitHub Actions to open PRs you have to allow it to do so at the bottom of the page at `Settings > Actions > General`.
- Since the latest *actually* published version of `eth-chains` is v1.0.0, I downgraded the package.json version to v2.0.0 (instead of v3.0.0).
- Merging this PR will already trigger the Publish Action.

### CODE REVIEW

**Comment by rkalis** [comment]
Hey @taylorjdawson, what do you think about this?

**Comment by rkalis** [comment]
Hey @taylorjdawson, any updates?

**Review by taylorjdawson — APPROVED** [review]
@rkalis apologies for the delay, here! Yes this is exactly what I was thinking, thanks for doing this, I'll merge and we can test out how it runs

**Review by taylorjdawson — APPROVED** [review]
@rkalis apologies for the delay, here! Yes this is exactly what I was thinking, thanks for doing this, I'll merge and we can test out how it runs

**Comment by rkalis** [comment]
Thanks for merging the PR. Getting it merged was taking too long for me, so I forked it to my own package about a month ago (https://github.com/RevokeCash/chains). The script has been working well so far. I'm surprised by how often breaking changes still happen tbh, basically every weekly run has resulted in a major version bump.

**Pull request merged**
