### PR TITLE
Add GitHub Actions workflow to update periodically

### PR DESCRIPTION
**Pull request by rkalis**
Add a GitHub Actions workflow called 'Update'

- 'Update' can be manually triggered, and will also run every Monday at midnight
- 'Update' will perform the following steps:
  - Generate new files through `yarn generate`
  - Execute `yarn build` to make sure there are no TypeScript errors introduced by the new data
  - Bump to new patch version
  - Commit changes and push to `main`
  - Publish to NPM with `yarn publish`
  - Create a tagged GitHub release for the new NPM version
  
Besides this new workflow, I also updated the typings so that they match the new data format of the chainId.network data. If the data format changes again, the workflow should fail in the `yarn build` step and requires manual intervention. As long as the data format doesn't change, this should publish a new patch release every week.

### CODE REVIEW

**Comment by rkalis** [comment]
Thinking about it, perhaps an automated `patch` release wouldn't be fitting, considering that if chain names change, that could be considered a breaking change. 🤔

**Comment by rkalis** [comment]
Perhaps every automated release should just be a new major release. Then you'd end up with quickly growing major version numbers, but I think that's probably fine.

**Comment by taylorjdawson** [comment]
@rkalis this is great thank you! Can you remove the `main.yml` github action? I'll get this merged in ASAP 🙌🏾

**Comment by rkalis** [comment]
Thanks, just did that!

What are your thoughts on having a weekly `major` vs `patch` release. The changes in data (e.g. change in chain name) would result in breaking changes to the enums (e.g. `ChainId.EthereumMainnet` might become `ChainId.Ethereum`).

I'd say we should either do a major release in the workflow, *or* we state in the README that `eth-chains` explicitly does not follow semver because of this workflow, and therefore recommend people to pin their version (`1.0.0` rather than `^1.0.0`).

**Comment by rkalis** [comment]
Hey @taylorjdawson, any thoughts on the above?

**Comment by taylorjdawson** [comment]
@rkalis Yea I like the idea of doing a major release every time. If we wanted to push this even further we could run a script that would check for breaking changes and if there are breaking changes it does a major release otherwise it does a minor release. Although do you think it would freak out developers do have really large numbers for major versions?

**Comment by rkalis** [comment]
Hmm yeah I think the idea of checking for breaking changes would be cool. I'd think that a breaking change would constitute any deletion in the diff (since additions wouldn't be breaking presumably). I think it should be possible to add that check to the build script.

I think there should be a note in the README about this automated release process so that people understand why there's high major version numbers. As long as that is explained, I don't think people would mind.

**Comment by rkalis** [comment]
I just updated the script to bump a "major" version if *any* deletions occur in the git diff, and a "minor" version if no deletions occur in the git diff. Let me know what you think @taylorjdawson

**Review by taylorjdawson — APPROVED** [review]

**Comment by taylorjdawson** [comment]
@rkalis Okay I think this looks good 🙌  Thanks again for the contribution, and sorry for the delay!

**Pull request merged**
