### PR TITLE
feat(chains): add Arbitrum mainnet

### PR DESCRIPTION
**Pull request by PierrickGT**
PR to add the Arbitrum mainnet chain.

### CODE REVIEW

**Comment by taylorjdawson** [comment]
@PierrickGT Thanks for this! Could you bump the version to `0.3.6` and then just double checking, did you test this change?

**Comment by PierrickGT** [comment]
> @PierrickGT Thanks for this! Could you bump the version to `0.3.6` and then just double checking, did you test this change?

@taylorjdawson I haven't tested this change but maybe this is the opportunity to add some unit tests to the project. How do you plan to unit test the different chains?

**Comment by taylorjdawson** [comment]
@PierrickGT I am closing this in leu of #9 -- It adds Arbitrum mainnet and all of the latest chains

**Comment by Breadcorn** [comment]
> PR to add the Arbitrum mainnet chain.
bc1q9846l20qagljl85xhucszstqlw4tk2usxrwyk5

**Pull request closed without merging**
