### PR TITLE
0.2.2 (feat): Configure for TS

### PR DESCRIPTION
**Pull request by taylorjdawson**
* Adds declaration files
  * Adds built dist folder

### CODE REVIEW

**Comment by amyboyd** [comment]
@taylorjdawson The latest version on NPM (0.2.2) doesn't have the `dist` folder in it. Could you please publish a new version with it?

This is a helpful little library BTW - thanks for making it.

**Comment by taylorjdawson** [comment]
@amyboyd Hey thanks for the feedback! I'll update the package today and post an update here 👍

Glad you found it helpful!

**Comment by taylorjdawson** [comment]
@amyboyd i updated and it should now be good to go, let me know if you have any further issues, and thanks again!

**Comment by amyboyd** [comment]
@taylorjdawson Thanks for the fix - 0.2.4 has `dist` now.

**Pull request merged**
